name: CI

on:
  push:
    paths:
      - .github/workflows/test.yml
    branches:
      - feature/*/*

jobs:
  selectenv:
    name: Select the environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Determine environment
      run: |
        if [[ "${{ github.ref }}" == refs/heads/feature/csaba-env/** ]]; then
          echo "::set-output name=environment::csaba-env"
        elif [[ "${{ github.ref }}" == refs/heads/feature/andrew-env/** ]]; then
          echo "::set-output name=environment::andrew-env"
        elif [[ "${{ github.ref }}" == refs/heads/feature/joshi-env/** ]]; then
          echo "::set-output name=environment::joshi-env"
        elif [[ "${{ github.ref }}" == refs/heads/feature/infrastructure/** ]]; then
          echo "::set-output name=environment::infrastructure"
        else
          echo "The branch name does not contain a valid environment."
        fi
  showenv:
    name: Show the selected environment
    runs-on: ubuntu-latest
    environment: ${{needs.selectenv.outputs.environment}}
    needs: selectenv
    steps:
    - name: Show command for environment
      run: |
        echo "This will deploy to ${{needs.selectenv.outputs.environment}}"
        echo "I added my group to the protection rules."
