name: CI

on:
  push:
    branches:
      - infrastructure/*

jobs:
  build:
    if: ${{ "${{github.ref}}" == refs/heads/infrastructure/* }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
