name: CI

on:
  push:
    paths:
      - .github/workflows/test.yml
    branches:
      - feature/*env
      - feature/my-infra

jobs:
  selectenv:
    name: Select the environment
    runs-on: ubuntu-latest
    outputs:
      myvariable: ${{steps.detenv.outputs.myvariable}}
    steps:
    - uses: actions/checkout@v2
    - name: Determine environment
      id: detenv
      run: |
        if [[ "${{ github.ref }}" == refs/heads/feature/*env ]]; then
          myenv=echo ${{ github.ref }} | awk -F '/' '{print $4}'
          echo "::set-output name=myvariable::${{ myenv }}"
        elif [[ "${{ github.ref }}" == refs/heads/feature/my-infra ]]; then
          echo "::set-output name=myvariable::my-infra"
        else
          echo "The branch name does not contain a valid environment."
        fi
  showenv:
    name: Show the selected environment
    runs-on: ubuntu-latest
    environment: ${{needs.selectenv.outputs.myvariable}}
    needs: selectenv
    steps:
    - name: Show command for environment
      run: |
        echo "This will deploy to ${{needs.selectenv.outputs.myvariable}}"
